export let baseDatos = [
    { id: 1, nombreActivo: 'Aire Acondicionado', ubicacion: 'Recepcion', estado: 'Activo' },
    { id: 2, nombreActivo: 'Televisor 55"', ubicacion: 'Sala de Juntas', estado: 'Activo' },
    { id: 3, nombreActivo: 'Computador Portátil HP', ubicacion: 'Oficina 1', estado: 'Activo' },
    { id: 4, nombreActivo: 'Impresora Epson L3150', ubicacion: 'Recepcion', estado: 'Activo' },
    { id: 5, nombreActivo: 'Celular Samsung A54', ubicacion: 'Oficina 2', estado: 'Activo' },
    { id: 6, nombreActivo: 'Router Wifi TP-Link', ubicacion: 'Cuarto de Redes', estado: 'Activo' },
    { id: 7, nombreActivo: 'Cámara de Seguridad', ubicacion: 'Entrada Principal', estado: 'Activo' },
    { id: 8, nombreActivo: 'Escritorio Ejecutivo', ubicacion: 'Gerencia', estado: 'Activo' },
    { id: 9, nombreActivo: 'Monitor Dell 24"', ubicacion: 'Oficina 3', estado: 'Activo' },
    { id: 10, nombreActivo: 'UPS APC 1000VA', ubicacion: 'Sala de Servidores', estado: 'Activo' },
    { id: 11, nombreActivo: 'Proyector Epson', ubicacion: 'Sala de Juntas', estado: 'Activo' },
    { id: 12, nombreActivo: 'Tablet Lenovo', ubicacion: 'Oficina 4', estado: 'Activo' },
    { id: 13, nombreActivo: 'Servidor Dell PowerEdge', ubicacion: 'Sala de Servidores', estado: 'Activo' },
    { id: 14, nombreActivo: 'Silla Ergonómica', ubicacion: 'Oficina 2', estado: 'Activo' },
    { id: 15, nombreActivo: 'Teléfono IP Cisco', ubicacion: 'Recepcion', estado: 'Activo' },
    { id: 16, nombreActivo: 'Disco Duro Externo 1TB', ubicacion: 'Oficina 1', estado: 'Activo' },
    { id: 17, nombreActivo: 'Switch de Red 24 Puertos', ubicacion: 'Cuarto de Redes', estado: 'Activo' },
    { id: 18, nombreActivo: 'Ventilador Industrial', ubicacion: 'Bodega', estado: 'Activo' },
    { id: 19, nombreActivo: 'Impresora Láser HP', ubicacion: 'Oficina 3', estado: 'Activo' },
    { id: 20, nombreActivo: 'Laptop Lenovo ThinkPad', ubicacion: 'Gerencia', estado: 'Activo' }
];
